# Generated by Django 4.2 on 2026-02-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_uploadedfile_hash_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Scan'), ('CLEAN', 'Clean'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
