# Generated by Django 4.2 on 2026-02-16 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0003_uploadedfile_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('MALWARE_DETECTED', 'Malware Detected'), ('INVALID_TYPE', 'Invalid File Type'), ('SIZE_LIMIT', 'Size Limit Exceeded'), ('DOWNLOAD', 'File Download'), ('LOGIN_FAIL', 'Login Failure')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
