# Generated by Django 4.2 on 2026-02-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_securityevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='original_filename',
            field=models.CharField(default='unknown_file', max_length=255),
        ),
    ]
